// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nzmsmcmfwtupjcpyyloz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im56bXNtY21md3R1cGpjcHl5bG96Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMxNjg1MDgsImV4cCI6MjA1ODc0NDUwOH0.YGxZOBcDurwXu16Pznx3csKmuYYmZ5m1vNDcX4igjEM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);